# Generated by Django 3.2.4 on 2021-06-16 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(max_length=255, unique=True, verbose_name='Username')),
                ('first_name', models.CharField(default='user', max_length=255, verbose_name='First Name')),
                ('last_name', models.CharField(default='user', max_length=255, verbose_name='Last Name')),
                ('phone', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.EmailField(default='e@email.com', max_length=254, unique=True, verbose_name='email address')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='')),
                ('user_type', models.CharField(default='user', max_length=50)),
                ('status', models.CharField(default='Active', max_length=50)),
                ('verified', models.BooleanField(blank=True, default=False)),
                ('occupation', models.CharField(blank=True, max_length=255, null=True)),
                ('company', models.CharField(blank=True, max_length=255, null=True)),
                ('bio', models.TextField(blank=True, null=True)),
                ('followers_count', models.IntegerField(default=0, editable=False)),
                ('follows_count', models.IntegerField(default=0, editable=False)),
                ('time_zone', models.CharField(default='EST', max_length=5)),
                ('updated_at', models.TimeField(auto_now=True, null=True)),
                ('created_at', models.TimeField(auto_now_add=True, null=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
